name: Hello World Pipeline

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  say-hello:
    runs-on: self-hosted  # This targets your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello World from GitHub Actions and Neha.a's self-hosted runner!"
